#
# (C) Eithery Lab, 2023
# Pershing CAPT file layout template
#
type: pershing.capt
format: fixed-length
description: >
  The Daily CAPS file (CAPS/CAPT) is produced on a trade and settlement date basis for firms that use the Commission and
  Payout System (CAPS) and is only available at the IBD level.
  The trade date files represent all trades and trade adjustments for a particular trade date, and produce three, four,
  or five record types for each trade, as noted in the file layouts below.
  The settlement date file represents only settled trades or trade adjustments that have settled on a given day.
  The fourth record is optional. It is sent only on request and relates to multi-currency records.

layout:
  record_size: 133
  record_id:
    pos: 4
  header:
    tag: BOF\x20{6}PERSHING
    file_type:
      tag: COMMISSION\x20TD
      pos: 19..36
    date:
      pos: 47..56
      format: MM/DD/CCYY
  trailer:
    tag: EOF\x20{6}PERSHING
    total_records:
      pos: 106..115

  records:
    - id: '1'
      name: DETAIL RECORD ONE
      fields:
        - ibd_number: 1..3
        - record_id:
            pos: 4
            value: '1'
        - trade_date:
            pos: 5..12
            type: date
            format: CCYYMMDD
        - trade_reference_number: 13..18
        - pershing_office_number: 19..21
        - account_number: 22..31
        - account_name: 32..63
        - buy_sell_indicator:
            pos: 64
            value: B|S|F
        - cancel_indicator:
            pos: 65
            value: X|\x20
        - caps_source:
            pos: 66..68
            value: PAR|XFE|XPS|XPT|TPS
        - trade_quantity:
            pos: 69..81
            type: num(18,4)
            format: s9(09)v9(04)
        - price:
            pos: 82..94
            type: num(18,7)
            format: s9(06)v9(07)
        - product_code: 95..98
        - cusip: 99..107
        - account_short_name: 108..117
        - order_type:
            pos: 118
            value: M|L|D|P|Z
        - miscellaneous_fee:
            pos: 119..131
            type: num(18,2)
            format: s9(11)v99
        - :blank: 132..133

    - id: '2'
      name: DETAIL RECORD TWO
      fields:
        - ibd_number: 1..3
        - record_id:
            pos: 4
            value: '2'
        - market_code:
            pos: 5
            value: [1-9]
        - blotter_code:
            pos: 6
            value: [0-35689]
        - security_type: 7
        - stock_symbol: 8..16
        - security_description: 17..56
        - cents_per_share:
            pos: 57..65
            type: num(18,4)
            format: 9(05)v9(04)
        - discount_percent:
            pos: 66..72
            type: num(18,2)
            format: s9(05)v99
        - paycode:
            pos: 73..74
            value: 00|87|88
        - master_client_mnemonic: 75..83
        - institutional_retail_indicator:
            pos: 84
            value: I|R
        - state_code: 85..87
        - commission_indicator:
            pos: 88..90
            value: CPS|FUL|MLT|N\/C|PFG
        - firm_trading_account: 91..99
        - posted_date:
            pos: 100..107
            type: date
            format: CCYYMMDD
        - settlement_date:
            pos: 108..115
            type: date
            format: CCYYMMDD
        - :blank: 116-132
        - recycle_indicator:
            pos: 133
            value: N|Y

    - id: '3'
      name: DETAIL RECORD THREE
      fields:
        - ibd_number: 1..3
        - record_id:
            pos: 4
            value: '3'
        - as_of_trade_indicator:
            pos: 5
            value: X|\x20
        - distribution_indicator:
            pos: 6
            value: D|S|\x20
        - explode_indicator:
            pos: 7
            value: 0|1
        - revenue_type:
            pos: 8
            value: A|C|F
        - ip_number: 9..11
        - ip_caps_revenue_center: 12..14
        - ip_caps_office_number: 15..17
        - ip_caps_split_percent:
            pos: 18..23
            type: num(18,4)
            format: s9(03)v9(03)
        - revenue_credited_to_ip:
            pos: 24..36
            type: num(18,2)
            format: s9(11)v99
        - pershing_charge:
            pos: 37..47
            type: num(18,2)
            format: s9(09)v99
        - from_ip_number: 48..50
        - caps_revenue_center_from_ip: 51..53
        - caps_office_number_from_ip: 54..56
        - total_order_commission:
            pos: 57..69
            type: num(18,2)
            format: s9(11)v99
        - spread_struddle:
            pos: 70
            value: \x20|[A-UZ09]
        - correction_code:
            pos: 71
            value: 1|5
        - security_modifier: 72
        - security_calculation_code: 73
        - principal:
            pos: 74..86
            type: num(18,2)
            format: s9(11)v99
        - crd_number: 87..93
        - source_of_input: 94..95
        - :blank: 96..120
        - service_charge_or_other_fee:
            pos: 121..133
            type: num(18,2)
            format: s9(11)v99

    - id: '4'
      name: DETAIL RECORD FOUR
      required: false
      fields:
        - ibd_number: 1..3
        - record_id:
            pos: 4
            value: '4'
        - currency_code: 5..7
        - currency_amount_of_revenue:
            pos: 8..25
            type: num(18,5)
            format: s9(15)v9(03)
        - foreign_exchange_rate:
            pos: 26..43
            type: num(18,10)
            format: s9(08)v9(10)
        - currency_multi_div_indicator:
            pos: 44
            value: M|D
        - ibd_settlement_fee:
            pos: 45..62
            type: num(18,5)
            format: s9(15)v9(03)
        - customer_settlement_fee:
            pos: 63..80
            type: num(18,5)
            format: s9(15)v9(03)
        - gloss_reference_number: 81..100
        - currency_amount_of_pershing_charge:
            pos: 101..111
            type: num(18,2)
            format: s9(09)v99
        - :blank: 112..133

    - id: '5'
      name: DETAIL RECORD FIVE
      required: false
      fields:
        - ibd_number: 1..3
        - record_id:
            pos: 4
            value: '5'
        - option_root_id: 5..10
        - expiration_date:
            pos: 11..16
            type: date
            format: YYMMDD
        - call_put_indicator:
            pos: 17
            value: B|C|D|E|L|M|P
        - strike_price:
            pos: 18..25
            type: num(18,5)
            format: s9(15)v9(03)
        - master_client_name: 26..57
        - :blank: 58..97
        - pershing_internal_order_reference_number: 98..117
        - :blank: 118..133
