name: ETL Toolkit CI
on:
  - push

jobs:
  type-check:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade core packages
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install tox
        run: python -m pip install tox

      - name: Run mypy type checker
        run: python -m tox -e tc

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade core packages
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install tox
        run: python -m pip install tox

      - name: Run flake8 linter
        run: python -m tox -e lint

  security-check:
    name: Security check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade core packages
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install tox
        run: python -m pip install tox

      - name: Run bandit security linter
        run: python -m tox -e sec

  test:
    name: Tests (${{ matrix.os }}, Python ${{ matrix.python.version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python:
          - version: '3.11'
          - version: '3.10'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python.version }}

      - name: Upgrade core packages
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install tox
        run: python -m pip install tox

      - name: Run pytest
        run: python -m tox -e test

  build:
    name: Build
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs:
      - type-check
      - lint
      - security-check
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade core packages
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install Poetry
        run: python -m pip install poetry

      - name: Install dependencies
        run: python -m poetry install

      - name: Build wheels
        run: python -m poetry build

      - uses: actions/upload-artifact@v3
        with:
          name: etl-toolkit-dist
          path: ./dist/

  publish:
    name: Publish
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs:
      - type-check
      - lint
      - security-check
      - test
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: etl-toolkit-dist
          path: ./dist/

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
