name: ETL Toolbox CI
on:
  - push

jobs:
  type-check:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade core packages
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install tox
        run: python -m pip install tox

      - name: Run mypy type checker
        run: python -m tox -e tc

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade core packages
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install tox
        run: python -m pip install tox

      - name: Run flake8 linter
        run: python -m tox -e lint

  test:
    name: Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python:
          - version: '3.11'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python.version }}

      - name: Upgrade core packages
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install tox
        run: python -m pip install tox

      - name: Run pytest
        run: python -m tox -e test

  security-check:
    name: Security check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade core packages
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install tox
        run: python -m pip install tox

      - name: Run bandit security linter
        run: python -m tox -e sec
